// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atqyqiqssfvpteuipnez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0cXlxaXFzc2Z2cHRldWlwbmV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0Nzk5MjQsImV4cCI6MjA3MDA1NTkyNH0.kw_F0WBDVpxGnM42qdffO2RQTNWtMGNfQMEM2cWEB4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});